name = "Hyde"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "An elegant open source and mobile first theme"
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.14

[author]
    name = "Johan"
    homepage = "https://www.jdeca57.com"

# If Porting existing theme
[original]
    author =  "Johan"
    homepage = "https://www.jdeca57.com/"
    repo = "https://www.github.com/mdo/hyde"
